// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var Alttracer = NewRuntimeAsset("alttracer.c", "398e26d750d0711ef6bc34b4ceb7b12e1bc9d4bf8f06874b8cdf4ae3a25b7637")
