// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var Alttracer = NewRuntimeAsset("alttracer.c", "65423ed8b208132d13665dea7dfb930fefee961c13ea7643f3c8474cf7464367")
