// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var Alttracer = NewRuntimeAsset("alttracer.c", "3d146a4d1505931eb6fcf202cffc35eac7944d2c8f6135dc721bf0a742366dd1")
