// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Classifier = NewRuntimeAsset("classifier.c", "238e9c17ed633ec2d1384c2fe1fda256c6526fad7652d0776e21a4e49fc4e180")
