// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Classifier = NewRuntimeAsset("classifier.c", "c4753342730af5202e8f418cc8a0fbd5b5c2c1706db3667cb7c20ce635ccb020")
