// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Classifier = NewRuntimeAsset("classifier.c", "6a285b9661924cf5a939d9df39c4a172701d32d342a9909f3f52e1ffd030a380")
