// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var Conntrack = NewRuntimeAsset("conntrack.c", "d6f8bacd6fd7818a98b5edf33c31652385aa1c7326815f6ddf785939d907ffee")
