// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var Conntrack = NewRuntimeAsset("conntrack.c", "8d48f413790cb968e92d9d748dfed76b1b6cf6beb82282f5a6105b85c008ad1d")
