// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var Conntrack = NewRuntimeAsset("conntrack.c", "a4a26df750e468db7cc5973f0705484682e7c4700d949e92fbc987230b535554")
