// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var GoTls = NewRuntimeAsset("go-tls.c", "02036178d0941de9a371d487c8fb0b114b139501b10a01c3679a4d82c52bb9c4")
