// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var GoTls = NewRuntimeAsset("go-tls.c", "2e3f32ad293d576dd15b0b35c2369a000af7daf33c328eba2c9865750c5c8065")
