// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var GoTls = NewRuntimeAsset("go-tls.c", "cc744600b054ca13dc9456a21b30bf7332afe2fe6b7584c948ec0a0f8b94f465")
