// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = NewRuntimeAsset("http.c", "531894c489abf1fd79daa540e49a77620ba3988dd93f86c2ce982c05781c137c")
