// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = NewRuntimeAsset("http.c", "bc5d2ab169f0081b21aba730957fe3235c016acc6b9a45a126e582042cd064ad")
