// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = NewRuntimeAsset("http.c", "4681590fe2537d61a647fcb001a9cddbd70bd2082dd2c070db21c72a621ced5c")
