// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var OomKill = NewRuntimeAsset("oom-kill.c", "19dd13e4527927c3f891b12f63462a9e4f575723c53737ef1ffb65300860f51a")
