// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Pidmapper = NewRuntimeAsset("pid_mapper.c", "fb51eda2e47324b3df5b0e95f9b27709e48f0bfdfd8d1aa5d08244dc1cf78266")
