// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "580eef348bba2104207c653f9d0856606336ab627e67db71d18aa9d85ef17485")
