// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "3cc0f2b51b5635eff449c9d00075e66585dd1a3a6139e3f7b059f8eea86f1769")
