// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "cf96a68b39fe0a38ebaa7faeb79a3de888bd9c3062b6596ea5b8b85348e0fda8")
