// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var Skbtracer = NewRuntimeAsset("skbtracer.c", "e9e8b0e6445be450d6c6b10167bd1c1b26e66a23e31999b33dcc98dede383042")
