// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var Skbtracer = NewRuntimeAsset("skbtracer.c", "5b7caa42c373710110f05fcbad0f3966277a2172dcff7712ae855fd5302a1691")
