// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var Skbtracer = NewRuntimeAsset("skbtracer.c", "7f4f50f2e9ec98b029b9c7f5f563f5d3ef2c6bd230c9e671c0cdfdf210461246")
