// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var TcpQueueLength = NewRuntimeAsset("tcp-queue-length.c", "78bdeb8d04095255029487ac1bd10aac28d74aa14675df3e607392a1872599ab")
