// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = NewRuntimeAsset("tracer.c", "b3f4edf943af0c710ef15a9e6f7885151440087a38515e1a8ff0b324241a0ca5")
