// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = NewRuntimeAsset("tracer.c", "f0619596eb615e9a6cac6f40f796999604e6d7747fe87b0ad850b2331fb1e41c")
