// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = NewRuntimeAsset("tracer.c", "cf14ea7689269dc674aa687ec2704ee1418fe04104695717d5cd3ba16c577bdb")
