// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package main

import "github.com/DataDog/datadog-agent/pkg/ebpf/bytecode/runtime"
var Netlinksnoop = runtime.NewRuntimeAsset("netlink_snoop.c", "6bbe612d5d9a3ac7dce137bd3c6d3a7579da54d70ec7456d67f4b90c19b54580")
