// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- -fsigned-char altkprobe_types.go

package ebpf

type Tuple struct {
	Family   uint8
	Protocol uint8
	Sport    uint16
	Dport    uint16
	Saddr    [16]uint8
	Daddr    [16]uint8
}
type FlowStats struct {
	Last_update uint64
	Sent_bytes  uint64
	Recv_bytes  uint64
}
type TCPFlow struct {
	Tup   Tuple
	Stats FlowStats
}
type SocketInfo struct {
	Ns        uint64
	Tgid      uint32
	Netns     uint32
	Direction uint8
	Pad_cgo_0 [7]byte
}
type TCPCloseEvent struct {
	Skp    uint64
	Flow   TCPFlow
	Skinfo SocketInfo
}
type UDPCloseEvent struct {
	Skp    uint64
	Skinfo SocketInfo
}
