// +build  linux

// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  probe

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( ActivityDump ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ActivityDump ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ActivityDump *ActivityDump
